import Consonant from '@/models/consonant'

export default [
  { symbol: 'ก', thai: 'ก ไก่', english: 'chicken', romanised: 'ko kai', tone: 'mid' },
  { symbol: 'ข', thai: 'ข ไข่', english: 'egg', romanised: 'kho kai', tone: 'high' },
  { symbol: 'ฃ', thai: 'ฃ ขวด', english: 'bottle', romanised: 'kho khuat', tone: 'high' },
  { symbol: 'ค', thai: 'ค ควาย', english: 'buffalo', romanised: 'kho khwai', tone: 'low' },
  { symbol: 'ฅ', thai: 'ฅ คน', english: 'person', romanised: 'kho khon', tone: 'low' },
  { symbol: 'ฆ', thai: 'ฆ ระฆัง', english: 'bell', romanised: 'kho ra-khang', tone: 'low' },
  { symbol: 'ง', thai: 'ง งู', english: 'snake', romanised: 'ngo ngu', tone: 'low' },
  { symbol: 'จ', thai: 'จ จาน', english: 'plate', romanised: 'cho chan', tone: 'mid' },
  { symbol: 'ฉ', thai: 'ฉ ฉิ่ง', english: 'cymbals', romanised: 'cho ching', tone: 'high' },
  { symbol: 'ช', thai: 'ช ช้าง', english: 'elephant', romanised: 'cho chang', tone: 'low' },
  { symbol: 'ซ', thai: 'ซ โซ่', english: 'chain', romanised: 'so so', tone: 'low' },
  { symbol: 'ฌ', thai: 'ฌ เฌอ', english: 'tree', romanised: 'cho choe', tone: 'low' },
  { symbol: 'ญ', thai: 'ญ หญิง', english: 'woman', romanised: 'yo ying', tone: 'low' },
  { symbol: 'ฎ', thai: 'ฎ ชฎา', english: 'headdress', romanised: 'do cha-da', tone: 'mid' },
  { symbol: 'ฏ', thai: 'ฏ ปฏัก', english: 'goad', romanised: 'to pa-tak', tone: 'mid' },
  { symbol: 'ฐ', thai: 'ฐ ฐาน', english: 'pedestal', romanised: 'tho than', tone: 'high' },
  { symbol: 'ฑ', thai: 'ฑ มณโฑ', english: 'montho', romanised: 'tho montho', tone: 'low' },
  { symbol: 'ฒ', thai: 'ฒ ผู้เฒ่า', english: 'elder', romanised: 'tho phu-thao', tone: 'low' },
  { symbol: 'ณ', thai: 'ณ เณร', english: 'samanera', romanised: 'no nen', tone: 'low' },
  { symbol: 'ด', thai: 'ด เด็ก', english: 'child', romanised: 'do dek', tone: 'mid' },
  { symbol: 'ต', thai: 'ต เต่า', english: 'turtle', romanised: 'to tao', tone: 'mid' },
  { symbol: 'ถ', thai: 'ถ ถุง', english: 'sack', romanised: 'tho thung', tone: 'high' },
  { symbol: 'ท', thai: 'ท ทหาร', english: 'soldier', romanised: 'tho thahan', tone: 'low' },
  { symbol: 'ธ', thai: 'ธ ธง', english: 'flag', romanised: 'tho thong', tone: 'low' },
  { symbol: 'น', thai: 'น หนู', english: 'mouse', romanised: 'no nu', tone: 'low' },
  { symbol: 'บ', thai: 'บ ใบไม้', english: 'leaf', romanised: 'bo baimai', tone: 'mid' },
  { symbol: 'ป', thai: 'ป ปลา', english: 'fish', romanised: 'po pla', tone: 'mid' },
  { symbol: 'ผ', thai: 'ผ ผึ้ง', english: 'bee', romanised: 'pho phueng', tone: 'high' },
  { symbol: 'ฝ', thai: 'ฝ ฝา', english: 'lid', romanised: 'fo fa', tone: 'high' },
  { symbol: 'พ', thai: 'พ พาน', english: 'phan', romanised: 'pho phan', tone: 'low' },
  { symbol: 'ฟ', thai: 'ฟ ฟัน', english: 'teeth', romanised: 'fo fan', tone: 'low' },
  { symbol: 'ภ', thai: 'ภ สำเภา', english: 'junk', romanised: 'pho sam-phao', tone: 'low' },
  { symbol: 'ม', thai: 'ม ม้า', english: 'horse', romanised: 'mo ma', tone: 'low' },
  { symbol: 'ย', thai: 'ย ยักษ์', english: 'giant', romanised: 'yo yak', tone: 'low' },
  { symbol: 'ร', thai: 'ร เรือ', english: 'boat', romanised: 'ro ruea', tone: 'low' },
  { symbol: 'ล', thai: 'ล ลิง', english: 'monkey', romanised: 'lo ling', tone: 'low' },
  { symbol: 'ว', thai: 'ว แหวน', english: 'ring', romanised: 'wo waen', tone: 'low' },
  { symbol: 'ศ', thai: 'ศ ศาลา', english: 'pavilion', romanised: 'so sala', tone: 'high' },
  { symbol: 'ษ', thai: 'ษ ฤๅษี', english: 'hermit', romanised: 'so rue-si', tone: 'high' },
  { symbol: 'ส', thai: 'ส เสือ', english: 'tiger', romanised: 'so suea', tone: 'high' },
  { symbol: 'ห', thai: 'ห หีบ', english: 'chest', romanised: 'ho hip', tone: 'high' },
  { symbol: 'ฬ', thai: 'ฬ จุฬา่', english: 'kite', romanised: 'lo chu-la', tone: 'low' },
  { symbol: 'อ', thai: 'อ อ่าง', english: 'basin', romanised: 'o ang', tone: 'mid' },
  { symbol: 'ฮ', thai: 'ฮ นกฮูก', english: 'owl', romanised: 'ho nok-huk', tone: 'low' }
] as Consonant[]
