export default [
	{ symbol: '๐', thai: '0', english: 'Zero', romanised: 'sun' },
	{ symbol: '๑', thai: '1', english: 'One', romanised: 'nueng' },
	{ symbol: '๒', thai: '2', english: 'Two', romanised: 'song' },
	{ symbol: '๓', thai: '3', english: 'Three', romanised: 'sam' },
	{ symbol: '๔', thai: '4', english: 'Four', romanised: 'si' },
	{ symbol: '๕', thai: '5', english: 'Five', romanised: 'ha' },
	{ symbol: '๖', thai: '6', english: 'Six', romanised: 'hok' },
	{ symbol: '๗', thai: '7', english: 'Seven', romanised: 'chet' },
	{ symbol: '๘', thai: '8', english: 'Eight', romanised: 'paet' },
	{ symbol: '๙', thai: '9', english: 'Nine', romanised: 'kao' },
	{ symbol: '๑๐', thai: '10', english: 'Ten', romanised: 'sip' },
	{ symbol: '๑๑', thai: '11', english: 'Eleven', romanised: 'sip et' },
	{ symbol: '๑๒', thai: '12', english: 'Twelve', romanised: 'sip song' },
	{ symbol: '๑๓', thai: '13', english: 'Thirteen', romanised: 'sip sam' },
	{ symbol: '๑๔', thai: '14', english: 'Fourteen', romanised: 'sip si' },
	{ symbol: '๑๕', thai: '15', english: 'Fifteen', romanised: 'sip ha' },
	{ symbol: '๑๖', thai: '16', english: 'Sixteen', romanised: 'sip hok' },
	{ symbol: '๑๗', thai: '17', english: 'Seventeen', romanised: 'sip chet' },
	{ symbol: '๑๘', thai: '18', english: 'Eighteen', romanised: 'sip paet' },
	{ symbol: '๑๙', thai: '19', english: 'Nineteen', romanised: 'sip kao' },
	{ symbol: '๒๐', thai: '20', english: 'Twenty', romanised: 'yi sip' },
	{ symbol: '๒๑', thai: '21', english: 'Twenty One', romanised: 'yi sip et' },
	{ symbol: '๒๒', thai: '22', english: 'Twenty Two', romanised: 'yi sip song' },
	{ symbol: '๒๓', thai: '23', english: 'Twenty Three', romanised: 'yi sip sam' },
	{ symbol: '๒๔', thai: '24', english: 'Twenty Four', romanised: 'yi sip si' },
	{ symbol: '๒๕', thai: '25', english: 'Twenty Five', romanised: 'yi sip ha' },
	{ symbol: '๒๖', thai: '26', english: 'Twenty Six', romanised: 'yi sip hok' },
	{ symbol: '๒๗', thai: '27', english: 'Twenty Seven', romanised: 'yi sip chet' },
	{ symbol: '๒๘', thai: '28', english: 'Twenty Eight', romanised: 'yi sip paet' },
	{ symbol: '๒๙', thai: '29', english: 'Twenty Nine', romanised: 'yi sip kao' },
	{ symbol: '๓๐', thai: '30', english: 'Thirty', romanised: 'sam sip' },
	{ symbol: '๔๐', thai: '40', english: 'Fourty', romanised: 'si sip' },
	{ symbol: '๕๐', thai: '50', english: 'Fifty', romanised: 'ha sip' },
	{ symbol: '๖๐', thai: '60', english: 'Sixty', romanised: 'hok sip' },
	{ symbol: '๗๐', thai: '70', english: 'Seventy', romanised: 'chet sip' },
	{ symbol: '๘๐', thai: '80', english: 'Eighty', romanised: 'paet sip' },
	{ symbol: '๙๐', thai: '90', english: 'Ninety', romanised: 'kao sip' },
	{ symbol: '๑๐๐', thai: '100', english: 'One Hundred', romanised: 'roi' },
	{ symbol: '๑๐๐๐', thai: '1000', english: 'One Thousand', romanised: 'phan' },
	{ symbol: '๑๐๐๐๐', thai: '10000', english: 'Ten Thousand', romanised: 'muen' },
	{ symbol: '๑๐๐๐๐๐', thai: '100000', english: 'Hundred Thousand', romanised: 'saen' },
	{ symbol: '๑๐๐๐๐๐๐', thai: '1000000', english: 'One Million', romanised: 'lan' }
]
