import Vowel from '@/models/vowel'

export default [
  { symbol: '◌ะ', thai: 'สระอะ', romanised: 'sara a wisanchani', length: 'short' },
  { symbol: '◌า', thai: 'สระอา', romanised: 'sara a lak khang', length: 'long' },
  { symbol: '◌ิ', thai: 'สระอิ', romanised: 'sara i', length: 'short' },
  { symbol: '◌ี', thai: 'สระอี', romanised: 'sara i', length: 'long' },
  { symbol: '◌ึ', thai: 'สระอึ', romanised: 'sara ue', length: 'short' },
  { symbol: '◌ือ', thai: 'สระอือ', romanised: 'sara ue', length: 'long' },
  { symbol: '◌ุ', thai: 'สระอุ', romanised: 'sara u', length: 'short' },
  { symbol: '◌ู', thai: 'สระอู', romanised: 'sara u', length: 'long' },
  { symbol: 'เ◌ะ', thai: 'สระเอะ', romanised: 'sara e', length: 'short' },
  { symbol: 'เ◌', thai: 'สระเอ', romanised: 'sara e', length: 'long' },
  { symbol: 'แ◌ะ', thai: 'สระแอะ', romanised: 'sara ae', length: 'short' },
  { symbol: 'แ◌', thai: 'สระแอ', romanised: 'sara ae', length: 'long' },
  { symbol: 'โ◌ะ', thai: 'สระโอะ', romanised: 'sara o', length: 'short' },
  { symbol: 'โ◌', thai: 'สระโอ', romanised: 'sara o', length: 'long' },
  { symbol: 'เ◌าะ', thai: 'สระเอาะ', romanised: 'sara o', length: 'short' },
  { symbol: '◌อ', thai: 'สระออ', romanised: 'sara o', length: 'long' },
  { symbol: 'เ◌อะ', thai: 'สระเออะ', romanised: 'sara oe', length: 'short' },
  { symbol: 'เ◌อ', thai: 'สระเออ', romanised: 'sara oe', length: 'long' },
  { symbol: 'เ◌ียะ', thai: 'สระเอียะ', romanised: 'sara ia', length: 'short' },
  { symbol: 'เ◌ีย', thai: 'สระเอีย', romanised: 'sara ia', length: 'long' },
  { symbol: 'เ◌ือะ', thai: 'สระเอือะ', romanised: 'sara uea', length: 'short' },
  { symbol: 'เ◌ือ', thai: 'สระเอือ', romanised: 'sara uea', length: 'long' },
  { symbol: '◌ัวะ', thai: 'สระอัวะ', romanised: 'sara ua', length: 'short' },
  { symbol: '◌ัว', thai: 'สระอัว', romanised: 'sara ua', length: 'long' },
  { symbol: '-ำ', thai: 'สระอำ', romanised: 'sara am', length: 'short' },
  { symbol: 'ใ◌', thai: 'สระใอ', romanised: 'sara ai mai muan', length: 'short' },
  { symbol: 'ไ◌', thai: 'สระไอ', romanised: 'sara ai mai malai', length: 'short' },
  { symbol: 'เ◌า', thai: 'สระเอา', romanised: 'sara ao', length: 'short' },
  { symbol: 'ฤ', thai: 'ตัว ฤ', romanised: 'tua rue', length: 'short' },
  { symbol: 'ฤๅ', thai: 'ฤๅ', romanised: 'tua rue', length: 'long' },
  { symbol: 'ฦ', thai: 'ฦ', romanised: 'tua lue', length: 'short' },
  { symbol: 'ฦๅ', thai: 'ฦๅ', romanised: 'tua lue', length: 'long' }
] as Vowel[]
